# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def shared_dependencies
  pod 'MJExtension', '~> 3.0.13'
#  pod 'AFNetworking', '~> 3.1.0'
  pod 'AFNetworking'
  pod 'YYModel'
  # pod 'TKCrashNilSafe/KVO', :path => "/Users/D/Remote/TKCrashNilSafe"
#  pod 'TKCrashNilSafe', :path => "/Users/D/Remote/TKCrashNilSafe"
end


target 'JSONToModel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for JSONToModel
  platform :osx, '10.9'
  shared_dependencies
  
#  pod 'YYModel'
end
